[[tests]]
name = "fib_rec"
input = ["./$project", "fib_rec", "10"]
expected = """
C: 55
Asm: 55
Emu: 55
"""
rubric = 5

[[tests]]
name = "get_bitseq"
input = ["./$project", "get_bitseq", "94116", "12", "15"]
expected = """
C: 6
Asm: 6
Emu: 6
"""
rubric = 5

[[tests]]
name = "is_pal"
input = ["./$project", "is_pal", "941171149"]
expected = """
C: is a palindrome
Asm: is a palindrome
Emu: is a palindrome
"""
rubric = 5

[[tests]]
name = "max3"
input = ["./$project", "max3", "2", "10", "8"]
expected = """
C: 10
Asm: 10
Emu: 10
"""
rubric = 5

[[tests]]
name = "merge_sort"
input = ["./$project", "merge_sort", "6", "4", "1", "2", "5", "3"]
expected = """
C: 1 2 3 4 5 6
Asm: 1 2 3 4 5 6
Emu: 1 2 3 4 5 6
"""
rubric = 13

[[tests]]
name = "midpoint"
input = ["./$project", "midpoint", "0", "4"]
expected = """
C: 2
Asm: 2
Emu: 2
"""
rubric = 5

[[tests]]
name = "quadratic"
input = ["./$project", "quadratic", "2", "4", "6", "8"]
expected = """
C: 36
Asm: 36
Emu: 36
"""
rubric = 4

[[tests]]
name = "sort"
input = ["./$project", "sort", "6", "4", "1", "2", "5", "3"]
expected = """
C: 6 5 4 3 2 1
Asm: 6 5 4 3 2 1
Emu: 6 5 4 3 2 1
"""
rubric = 13

[[tests]]
name = "to_upper"
case_sensitive = true
input = ["./$project", "to_upper", "FooBar"]
expected = """
C: FOOBAR
Asm: FOOBAR
Emu: FOOBAR
"""
rubric = 5

[[tests]]
name = "quadratic_analysis"
input = ["./$project", "-a", "quadratic", "2", "4", "6", "8"]
expected = """
C: 36
Asm: 36
Emu: 36
=== Analysis
Instructions Executed  = 6
R-type + I-type        = 5 (83.33%)
Loads                  = 0 (0.00%)
Stores                 = 0 (0.00%)
Jumps/JAL/JALR         = 1 (16.67%)
Conditional branches   = 0 (0.00%)
  Branches taken       = 0 (0.00%)
  Branches not taken   = 0 (0.00%)
"""
rubric = 4

[[tests]]
name = "fib_analysis"
input = ["./$project", "-a", "fib_rec", "10"]
expected = """
C: 55
Asm: 55
Emu: 55
=== Analysis
Instructions Executed  = 1675
R-type + I-type        = 617 (36.84%)
Loads                  = 264 (15.76%)
Stores                 = 264 (15.76%)
Jumps/JAL/JALR         = 353 (21.07%)
Conditional branches   = 177 (10.57%)
  Branches taken       = 88 (49.72%)
  Branches not taken   = 89 (50.28%)
"""
rubric = 4

[[tests]]
name = "fib_dm_8"
input = ["./$project", "-dm", "8", "fib_rec", "10"]
expected = """
C: 55
Asm: 55
Emu: 55
=== Cache
Type          = direct mapped
Size          = 8 slots
References    = 2119
Hits          = 941 (44.41% hit ratio)
Misses        = 1178 (55.59% miss ratio)
Misses (cold) = 8
Misses (hot)  = 1170
% Used        = 100.00%
"""
rubric = 4

[[tests]]
name = "to_upper_sa_16"
input = ["./$project", "-sa", "16", "to_upper", "foobar"]
expected = """
C: FOOBAR
Asm: FOOBAR
Emu: FOOBAR
=== Cache
Type          = 4-way set associative
Size          = 16 slots
References    = 71
Hits          = 58 (81.69% hit ratio)
Misses        = 13 (18.31% miss ratio)
Misses (cold) = 13
Misses (hot)  = 0
% Used        = 81.25%
"""
rubric = 4

[[tests]]
name = "is_pal_analysis_sa_32"
input = ["./$project", "-a", "-sa", "32", "is_pal", "able was i ere i saw elba"]
expected = """
C: is a palindrome
Asm: is a palindrome
Emu: is a palindrome
=== Analysis
Instructions Executed  = 172
R-type + I-type        = 73 (42.44%)
Loads                  = 36 (20.93%)
Stores                 = 12 (6.98%)
Jumps/JAL/JALR         = 26 (15.12%)
Conditional branches   = 25 (14.53%)
  Branches taken       = 24 (96.00%)
  Branches not taken   = 1 (4.00%)
=== Cache
Type          = 4-way set associative
Size          = 32 slots
References    = 189
Hits          = 172 (91.01% hit ratio)
Misses        = 17 (8.99% miss ratio)
Misses (cold) = 17
Misses (hot)  = 0
% Used        = 53.12%
"""
rubric = 4
