[[tests]]
name = "01"
input = ["./$project", "3", "-o", "2"]
expected = "0b11"
rubric = 5

[[tests]]
name = "01"
input = ["./$project", "132789", "-o", "2"]
expected = "0b11"
rubric = 5

[[tests]]
name = "01"
input = ["./$project", "0xa", "-o", "10"]
expected = "10"
rubric = 5
