[project]
build = "none"
strip_output = """
Use default settings!
"""

[[tests]]
name = "00-add-r"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/00-add-r-test.dig"]
expected = """
00-add-r-test: passed
"""
rubric = 2

[[tests]]
name = "01-add-i"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/01-add-i-test.dig"]
expected = """
01-add-i-test: passed
"""
rubric = 2

[[tests]]
name = "02-sll-r"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/02-sll-r-test.dig"]
expected = """
02-sll-r-test: passed
"""
rubric = 2

[[tests]]
name = "03-sll-i"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/03-sll-i-test.dig"]
expected = """
03-sll-i-test: passed
"""
rubric = 2

[[tests]]
name = "04-srl-r"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/04-srl-r-test.dig"]
expected = """
04-srl-r-test: passed
"""
rubric = 2

[[tests]]
name = "05-srl-i"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/05-srl-i-test.dig"]
expected = """
05-srl-i-test: passed
"""
rubric = 2

[[tests]]
name = "06-sd-ld"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/06-sd-ld-test.dig"]
expected = """
06-sd-ld-test: passed
"""
rubric = 2

[[tests]]
name = "07-sw-lw"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/07-sw-lw-test.dig"]
expected = """
07-sw-lw-test: passed
"""
rubric = 2

[[tests]]
name = "08-jal"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/08-jal-test.dig"]
expected = """
08-jal-test: passed
"""
rubric = 2

[[tests]]
name = "09-j"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/09-j-test.dig"]
expected = """
09-j-test: passed
"""
rubric = 2

# [[tests]]
# name = "06-mem-imm"
# input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/06-mem-imm-test.dig"]
# expected = """
# 06-mem-imm-test: passed
# """
# rubric = 2
# 
# [[tests]]
# name = "07-mem-shift-reg"
# input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/07-mem-shift-reg-test.dig"]
# expected = """
# 07-mem-shift-reg-test: passed
# """
# rubric = 2
# 
# [[tests]]
# name = "08-blbx"
# input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/08-blbx-test.dig"]
# expected = """
# 08-blbx-test: passed
# """
# rubric = 2
# 
# [[tests]]
# name = "09-b"
# input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/09-b-test.dig"]
# expected = """
# 09-b-test: passed
# """
# rubric = 2
# 
# [[tests]]
# name = "10-beq"
# input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/10-beq-test.dig"]
# expected = """
# 10-beq-test: passed
# """
# rubric = 2
# 
# [[tests]]
# name = "11-ble"
# input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/11-ble-test.dig"]
# expected = """
# 11-ble-test: passed
# """
# rubric = 2
# 
# [[tests]]
# name = "12-bgt"
# input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/12-bgt-test.dig"]
# expected = """
# 12-bgt-test: passed
# """
# rubric = 2
# 
# [[tests]]
# name = "13-mul"
# input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/13-mul-test.dig"]
# expected = """
# 13-mul-test: passed
# """
# rubric = 2
# 
# [[tests]]
# name = "14-rsb"
# input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/14-rsb-test.dig"]
# expected = """
# 14-rsb-test: passed
# """
# rubric = 2
# 
# [[tests]]
# name = "15-quadratic"
# input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/15-quadratic-test.dig"]
# expected = """
# 15-quadratic-test: passed
# """
# rubric = 5
# 
# [[tests]]
# name = "16-get_bitseq"
# input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/16-get-bitseq-test.dig"]
# expected = """
# 16-get-bitseq-test: passed
# """
# rubric = 5
# 
# [[tests]]
# name = "17-max3"
# input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/17-max3-test.dig"]
# expected = """
# 17-max3-test: passed
# """
# rubric = 5
# 
# [[tests]]
# name = "18-fib-rec"
# input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/18-fib-rec-test.dig"]
# expected = """
# 18-fib-rec-test: passed
# """
# rubric = 5
